MyFood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings          
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve  #追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('user/<int:pk>/', views.users_detail, name='users_detail'),
    path('signup/', views.signup, name='signup'),
    path('shops/new/', views.shops_new, name='shops_new'),
    path('shops/<int:pk>/', views.shops_detail, name='shops_detail'), 
    path('shops/<int:pk>/edit/', views.shops_edit, name='shops_edit'),
    path('shops/<int:pk>/delete/', views.shops_delete, name='shops_delete'),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search/', views.go_search, name='go_search'),    #必ずviewを経由しないと動かない？
    path('mylist_search/', views.go_mylist_search, name='go_mylist_search'),    #必ずviewを経由しないと動かない？
    path('mylist_search/result/', views.mylist_search, name='mylist_search'),
    path('search/result/', views.shops_search, name='shops_search'),  
    path('search/result/map', views.map_output, name='map_output'),  
    
]

app/templates/app/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Ｍｙグルメ</title>
    
</head>

<body>
    <header>
        <div class="container">
            <h1><a href="{% url 'app:index' %}">Ｍｙグルメ</a></h1>
            <div class="header-menu">
                <a href="{% url 'app:go_mylist_search' %}">マイリストから検索</a>
                {% comment %} <a href="{% url 'app:go_place_search' %}">現在地から検索</a> {% endcomment %}
                <a href="{% url 'app:shops_new' %}">手動で登録</a>
                <a href="{% url 'app:go_search' %}">URLから登録</a>
                <a href="{% url 'app:signup' %}">ユーザー登録</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'app:logout' %}">ログアウト</a>
                    ({{request.user.username}}でログイン中)  
                {% else %}
                    <a href="{% url 'app:login' %}">ログイン</a>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="container">
        {% for message in messages %}
            <p class="message-success">{{ message }}</p>
        {% endfor %}        
        {% block content %}{% endblock %}
    </div>
</body>

</html>

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<h2>マイリスト</h2>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% for shop in shops %}
<div class="item">
    <a href="{% url 'app:shops_detail' shop.id %}">
    <p><img src="{{shop.state.symbol}}" width="20" height="20" class="shop-photo"> 
    <span class = "item-title">
    {{shop.evaluate}} &emsp;  {{shop.name}}</p></a>
    </span>
    {% comment %} <p>{{shop.evaluate}}</p> {% endcomment %}
    <p>{{shop.station}}</p>
    <p>{{shop.genre}}</p>    
    <p>{{shop.comment}}</p>
    {% comment %} {% if shop.photo  %}
    <img src="{{ shop.photo.url }}"  width="193" height="130" class="shop-photo">
    {% else %}
    <img src="/static/photos/no_image.png"  width="193" height="130" class="shop-photo">    
    {% endif %} {% endcomment %}
    {% comment %} <img src="data:image/jpeg;base64,{{shop.photo_binary}}}  width="193" height="130" class="shop-photo">     {% endcomment %}
</div>
{% endfor %}

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

<form class="form-signin" method="post">{% csrf_token %}
    {% if form.errors %}
        <p>ユーザー名かパスワードが間違っています。もう一度入力してください。</p>
    {% endif %}
    <h2>ログイン</h2>
    <label>ユーザー名</label>
    <input name="username">
    <br>
    <label>パスワード</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="ログイン">
</form>

{% endblock %}

app/templates/app/map.html
<!DOCTYPE html>
<head>    
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <script>L_PREFER_CANVAS=false; L_NO_TOUCH=false; L_DISABLE_3D=false;</script>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/leaflet.awesome.rotate.css"/>
    <style>html, body {width: 100%;height: 100%;margin: 0;padding: 0;}</style>
    <style>#map {position:absolute;top:0;bottom:0;right:0;left:0;}</style>
    
    <meta name="viewport" content="width=device-width,
        initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <style>#map_321d011b33d045349ff0d32f1a828a0c {
        position: relative;
        width: 100.0%;
        height: 100.0%;
        left: 0.0%;
        top: 0.0%;
        }
    </style>
</head>
<body>    
    
    <div class="folium-map" id="map_321d011b33d045349ff0d32f1a828a0c" ></div>
</body>
<script>    
    
    
        var bounds = null;
    

    var map_321d011b33d045349ff0d32f1a828a0c = L.map(
        'map_321d011b33d045349ff0d32f1a828a0c', {
        center: [35.691108, 139.702107],
        zoom: 15,
        maxBounds: bounds,
        layers: [],
        worldCopyJump: false,
        crs: L.CRS.EPSG3857,
        zoomControl: true,
        });


    
    var tile_layer_b3b1ed72557a45ada05b353281731834 = L.tileLayer(
        'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        {
        "attribution": null,
        "detectRetina": false,
        "maxNativeZoom": 18,
        "maxZoom": 18,
        "minZoom": 0,
        "noWrap": false,
        "opacity": 1,
        "subdomains": "abc",
        "tms": false
}).addTo(map_321d011b33d045349ff0d32f1a828a0c);
    
        var marker_d9dd229e8bb34410ae551807d56c9d95 = L.marker(
            [35.691108, 139.702107],
            {
                icon: new L.Icon.Default(),
                }
            ).addTo(map_321d011b33d045349ff0d32f1a828a0c);
        
    

                var icon_dc241d67046546439c19b1cb2f4d1c50 = L.AwesomeMarkers.icon({
                    icon: 'info-sign',
                    iconColor: 'white',
                    markerColor: 'blue',
                    prefix: 'glyphicon',
                    extraClasses: 'fa-rotate-0'
                    });
                marker_d9dd229e8bb34410ae551807d56c9d95.setIcon(icon_dc241d67046546439c19b1cb2f4d1c50);
            
    
            var popup_afd9367ec7254e4f8edc3a669456ac9f = L.popup({maxWidth: '100%'
            
            });

            
                var html_0090fde008894aaba2968a5d725d0307 = $(`<div id="html_0090fde008894aaba2968a5d725d0307" style="width: 100.0%; height: 100.0%;"><div style="white-space:nowrap;">評価：3.25<br>京町恋しぐれ 新宿 本館<br>ラーメン<br>昼：<br>夜：</div></div>`)[0];
                popup_afd9367ec7254e4f8edc3a669456ac9f.setContent(html_0090fde008894aaba2968a5d725d0307);
            

            marker_d9dd229e8bb34410ae551807d56c9d95.bindPopup(popup_afd9367ec7254e4f8edc3a669456ac9f)
            ;

            
        
    
        var marker_a3e48e4f84074899a245c2417664f5ee = L.marker(
            [35.695485, 139.698058],
            {
                icon: new L.Icon.Default(),
                }
            ).addTo(map_321d011b33d045349ff0d32f1a828a0c);
        
    

                var icon_1dc0d63f7d2547b4806c0147e4d4f5fc = L.AwesomeMarkers.icon({
                    icon: 'info-sign',
                    iconColor: 'white',
                    markerColor: 'red',
                    prefix: 'glyphicon',
                    extraClasses: 'fa-rotate-0'
                    });
                marker_a3e48e4f84074899a245c2417664f5ee.setIcon(icon_1dc0d63f7d2547b4806c0147e4d4f5fc);
            
    
            var popup_4b829a6bc6634b93a1ea08c958eb9c2d = L.popup({maxWidth: '100%'
            
            });

            
                var html_ad90a4b8181f44a8936fcddaf275c7f8 = $(`<div id="html_ad90a4b8181f44a8936fcddaf275c7f8" style="width: 100.0%; height: 100.0%;"><div style="white-space:nowrap;">評価：3.64<br>えびそば 一幻 新宿店<br>ラーメン<br>昼：～￥999<br>夜：～￥999</div></div>`)[0];
                popup_4b829a6bc6634b93a1ea08c958eb9c2d.setContent(html_ad90a4b8181f44a8936fcddaf275c7f8);
            

            marker_a3e48e4f84074899a245c2417664f5ee.bindPopup(popup_4b829a6bc6634b93a1ea08c958eb9c2d)
            ;

            
        
</script>

app/templates/app/mylist_search.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>




    <form action="{% url 'app:mylist_search' %}" method="GET" enctype="multipart/form-data">{% csrf_token %}
    <table>
        <tr>
            <th>店名</th>
            <td>{{ form.name }}</td>
        </tr>    
        <tr>
            <th>駅</th>
            <td>{{ form.station }}</td>
        </tr>
        <tr>
            <th>ジャンル</th>
            <td>{{ form.genre }}</td>
        </tr>        
    </table>        
    <input type="submit" value="検索">
    </form>
{% endblock %}

app/templates/app/search_result.html
{% extends 'app/base.html' %}

{% block content %}

<h2>検索結果</h2>
<form action="{% url 'app:map_output' %}" method="GET" target="_blank"　enctype="multipart/form-data">{% csrf_token %}
<button><a class="btn" >検索結果をマップに出力</a></button> 

</form>
{% for shop in shops %}

<a href="{% url 'app:shops_detail' shop.id %}">
    <p>{{shop.name}}</p>
    <p>{{shop.evaluate}}</p>
    <p>{{shop.genre}}</p>
    <p>{{shop.comment}}</p>
    {% comment %} {% if shop.photo  %}
    <img src="{{ shop.photo.url }}"  width="193" height="130" class="shop-photo">
    {% else %}
    <img src="/media/photos/no_image.png"  width="193" height="130" class="shop-photo">    
    {% endif %} {% endcomment %}
{% endfor %}

{% endblock %}

app/templates/app/shops_detail.html
{% extends 'app/base.html' %}

{% block content %}

<div class="shop-detail">

<div class="shop-info">
    
</div>

<h2><a href={{shop.url}}>{{ shop.name }}</a></h2>
<p>評価　　:{{ shop.evaluate }}　(口コミ{{ shop.kuchikomi }}件)</p>
<p>駅　　　:{{ shop.station }}</p>
<p>ジャンル:{{ shop.genre }}</p>
<p>定休日　:{{ shop.teikyu }}</p>
<p>昼予算:{{ shop.lunch_bud }}</p>
<p>夜予算:{{ shop.dinner_bud }}</p>
<p>コメント:{{ shop.comment }}</p>
{% comment %} {% if shop.photo  %}
<img src="{{ shop.photo.url }}"  width="193" height="130" class="shop-photo">
{% else %}
<img src="/media/photos/no_image.png"  width="193" height="130" class="shop-photo">    
{% endif %} {% endcomment %}

<!-- 編集ボタン　-->
<form  action="{% url 'app:shops_edit' shop.id %}">{% csrf_token %}
<button><a class="btn" >編集</a></button>

</form>
<!-- 削除ボタン　-->
<form method="post" action="{% url 'app:shops_delete' shop.id %}">{% csrf_token %}
    <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
</form>

</div>
{% endblock %}
        

app/templates/app/shops_edit.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

	<form action="{% url 'app:shops_edit' shop.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
{% comment %} 以下のtableはshops_newと合わせること！ {% endcomment %}
    <table>
        <tr>
            <th>店名</th>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <th>ジャンル</th>
            <td>{{ form.genre }}</td>
        </tr>
        <tr>
            <th>評価</th>
            <td>{{ form.evaluate }}</td>
        </tr>
        <tr>
            <th>口コミ数</th>
            <td>{{ form.kuchikomi }}</td>
        </tr>

        <tr>
            <th>駅</th>
            <td>{{ form.station }}</td>
        </tr>
        <tr>
            <th>昼予算</th>
            <td>{{ form.lunch_bud }}</td>
        </tr>
        <tr>
            <th>夜予算</th>
            <td>{{ form.dinner_bud }}</td>
        </tr>
        <tr>
            <th>定休日</th>
            <td>{{ form.teikyu }}</td>
        </tr>

        <tr>
            <th>URL</th>
            <td>{{ form.url }}</td>
        </tr>        
        {% comment %} <tr>
            <th>写真</th>
            <td>{{ form.photo }}</td>
        </tr> {% endcomment %}
        {% comment %} <tr>
            <th>写真</th>
            <td><input type="file" name="pic"></td>
        </tr> {% endcomment %}

        <tr>
            <th>状態</th>
            <td>{{ form.state }}</td>
        </tr>
        <tr>
            <th>コメント</th>
            <td>{{ form.comment }}</td>
        </tr>        
    </table>
    {{form.coordinate.as_hidden}}
    {{form.user.as_hidden}}
    <button type="submit" class="btn">変更</button>
</form>

{% endblock %}

app/templates/app/shops_editbk.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

	<form action="{% url 'app:shops_edt' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
	<button type="submit" class="btn">検索</button>
    <table>
        <tr>
            <th>店名</th>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <th>評価</th>
            <td>{{ form.evaluate }}</td>
        </tr>
        <tr>
            <th>駅</th>
            <td>{{ form.station }}</td>
        </tr>
        <tr>
            <th>ジャンル</th>
            <td>{{ form.genre }}</td>
        </tr>
        <tr>
            <th>URL</th>
            <td>{{ form.url }}</td>
        </tr>        
        <tr>
            <th>写真</th>
            <td>{{ form.photo }}</td>
        </tr>
        <tr>
            <th>状態</th>
            <td>{{ form.state }}</td>
        </tr>
        <tr>
            <th>コメント</th>
            <td>{{ form.comment }}</td>
        </tr>        
    </table>
    {{form.coordinate.as_hidden}}
    {{form.user.as_hidden}}
    <button type="submit" class="btn">保存</button>
</form>

{% endblock %}

app/templates/app/shops_new.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

	<form action="{% url 'app:shops_new' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
        <tr>
            <th>店名</th>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <th>ジャンル</th>
            <td>{{ form.genre }}</td>
        </tr>
        <tr>
            <th>評価</th>
            <td>{{ form.evaluate }}</td>
        </tr>
        <tr>
            <th>口コミ数</th>
            <td>{{ form.kuchikomi }}</td>
        </tr>

        <tr>
            <th>駅</th>
            <td>{{ form.station }}</td>
        </tr>
        <tr>
            <th>昼予算</th>
            <td>{{ form.lunch_bud }}</td>
        </tr>
        <tr>
            <th>夜予算</th>
            <td>{{ form.dinner_bud }}</td>
        </tr>
        <tr>
            <th>定休日</th>
            <td>{{ form.teikyu }}</td>
        </tr>

        <tr>
            <th>URL</th>
            <td>{{ form.url }}</td>
        </tr>        
        {% comment %} <tr>
            <th>写真</th>
            <td>{{ form.photo }}</td>
        </tr> {% endcomment %}
        {% comment %} <tr>
            <th>写真</th>
            <td><input type="file" name="pic"></td>
        </tr> {% endcomment %}

        <tr>
            <th>状態</th>
            <td>{{ form.state }}</td>
        </tr>
        <tr>
            <th>コメント</th>
            <td>{{ form.comment }}</td>
        </tr>        
    </table>
    {{form.coordinate.as_hidden}}
    {{form.user.as_hidden}}
    <button type="submit" class="btn">保存</button>
</form>

{% endblock %}

app/templates/app/shops_search.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>




    <form action="{% url 'app:shops_search' %}" method="get">
        <label>URL<input type="text" size="100" name="search_url"></label>
        <input type="submit" value="検索">
    </form>
{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}

{% block content %}

<h2>ユーザー登録</h2>

<form method="post" action="{% url 'app:signup' %}">{% csrf_token %}
    <label>ユーザー名</label>
    {{ form.username }}
    {{ form.username.errors }}
    <br>
    <label>パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <br>
    <label>パスワード(確認)</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
    <br>
    <input type="submit" value="登録する">
</form>

<p><a href="{% url 'app:login' %}">ログインはこちら</a></p>

{% endblock %}

app/templates/app/success.html
{% extends 'app/base.html' %}

{% block content %}





{% endblock %}

app/templates/app/users_detail.html
<h2 class="user-name">@{{ user.username }}</h2>

{% for shop in shops %}
<a href="{% url 'app:shops_detail' shop.id %}">
    <img src="{{ shop.photo.url }}" class="shop-photo">
</a>
{% endfor %}